services:
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: frontend
    restart: always
  healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:3001" ]
      interval: 30s
      timeout: 10s
      retries: 5