name: trascendence

networks:
  backend:
    driver: bridge

services:
  frontend:
    extends:
      file: ./frontend/docker/frontend.docker-compose.yml
      service: frontend
    ports:
      - "5173:5173"

  tournament:
    extends:
      file: ./backend/tournament/docker/tournament.docker-compose.yml
      service: tournament
    ports:
      - "5174:3000"

  login:
    extends:
      file: ./backend/login/docker/login.docker-compose.yml
      service: login
    ports:
      - "5175:3000"