name: trascendence

services:
  api:
    extends:
      file: backend/api/docker/api.docker-compose.yml
      service: api
    ports:
      - "443:443"
    links:
      - frontend
      - auth
      - tournaments
    depends_on:
      - frontend
      - auth
      - tournaments

  frontend:
    env_file: .env
    extends:
      file: frontend/docker/frontend.docker-compose.yml
      service: frontend
    environment:
      - PORT=${FRONTEND_PORT}
    expose:
      - "${FRONTEND_PORT}"

  auth:
    env_file: .env
    extends:
      file: backend/auth/docker/auth.docker-compose.yml
      service: auth
    environment:
      - PORT=${AUTH_PORT}
    expose:
      - "${AUTH_PORT}"

  tournaments:
    env_file: .env
    extends:
      file: backend/tournaments/docker/tournaments.docker-compose.yml
      service: tournaments
    environment:
      - PORT=${TOURNAMENTS_PORT}
    expose:
      - "${TOURNAMENTS_PORT}"

  ssl-certs:
    build:
      context: backend/ssl-certs
      dockerfile: docker/ssl-certs.Dockerfile
    volumes:
      - ./backend/ssl-certs:/certs

volumes:
  auth_data:
  tournaments_data: