name: trascendence
services:
  proxy:
    depends_on:
      - frontend
      - api
    ports:
      - '443:443'
    volumes:
      - ./common/ssl-certs/output:/certs:ro
    extends:
      file: backend/proxy/docker/docker-compose.proxy.yml
      service: proxy

  frontend:
    extends:
      file: frontend/docker/docker-compose.frontend.yml
      service: frontend

  api:
    depends_on:
      - auth
      - tournaments
    volumes:
      - ./common/ssl-certs/output:/certs:ro
    extends:
      file: backend/api/docker/docker-compose.api.yml
      service: api

  auth:
    volumes:
      - ./common/ssl-certs/output:/certs:ro
    extends:
      file: backend/auth/docker/docker-compose.auth.yml
      service: auth

  tournaments:
    volumes:
      - ./common/ssl-certs/output:/certs:ro
    extends:
      file: backend/tournaments/docker/docker-compose.tournaments.yml
      service: tournaments

  ssl-certs:
    extends:
      file: common/ssl-certs/docker/docker-compose.ssl-certs.yml
      service: ssl-certs

volumes:
  auth_data: null
  tournaments_data: null
