services:
  proxy:
    container_name: proxy
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile
    restart: always
    volumes:
      - ../../ssl-certs:/certs:ro
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
