services:
  tournaments:
    container_name: tournaments
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile
    restart: always
    volumes:
      - tournaments_data:/var/lib/app
