services:
  tournaments:
    build:
      context: ../src
      dockerfile: ../docker/tournaments.Dockerfile
    container_name: tournaments
    volumes:
      - tournaments_data:/var/lib/app
    restart: always