version: "3.9"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"   # dev HTTP
      # - "443:443"   # keep commented; use when we go back to HTTPS
      # - "${GATEWAY_PORT}:443"
    volumes:
      - ./certs:/certs:ro
    environment:
      - NODE_ENV=development
      - AUTH_URL=http://auth:${AUTH_PORT}
      - TOURN_URL=http://tournaments:3003
      - AUTH_JWT_SECRET=auth_jwt_secret_dev_2025!!
      - USE_HTTP=1
      - PORT=3000
    depends_on:
      - auth
      - tournaments

  auth:
    build: ./auth
    expose:
      - "${AUTH_PORT}"
    environment:
      - NODE_ENV=development
      - PORT=${AUTH_PORT}
      - AUTH_DB_PATH=/var/lib/app/auth.db
      - AUTH_JWT_SECRET=auth_jwt_secret_dev_2025!! 
    volumes:
      - auth_data:/var/lib/app

  tournaments:
    build: ./tournaments
    expose:
      - "3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - TOURN_DB_PATH=/var/lib/app/tournaments.db
      - AUTH_INTERNAL_URL=http://auth:${AUTH_PORT}
    volumes:
      - tournaments_data:/var/lib/app


volumes:
  auth_data:
  tournaments_data:
