version: "3.9"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "${GATEWAY_PORT}:443"
    volumes:
      - ./certs:/certs:ro
    environment:
      - NODE_ENV=development
      - AUTH_URL=http://auth:${AUTH_PORT}
      - TOURN_URL=http://tournaments:3003
    depends_on:
      - auth
      - tournaments

  auth:
    build: ./auth
    expose:
      - "${AUTH_PORT}"
    environment:
      - NODE_ENV=development
      - PORT=${AUTH_PORT}
    volumes:
      - auth_data:/var/lib/app

  tournaments:
    build: ./tournaments
    expose:
      - "3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - TOURN_DB_PATH=/var/lib/app/tournaments.db
      - AUTH_INTERNAL_URL=http://auth:${AUTH_PORT}
    volumes:
      - tournaments_data:/var/lib/app


volumes:
  auth_data:
  tournaments_data:
