# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rzhdanov <rzhdanov@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/09/19 02:36:59 by rzhdanov          #+#    #+#              #
#    Updated: 2025/09/19 03:16:38 by rzhdanov         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

dev-up:
	docker compose up --build

dev-down:
	docker compose down -v

logs:
	docker compose logs -f